spring:
  application:
    name: dubbo-demo-provider

dubbo:
  scan:
    base-packages: com.lzq.demo.provider
  protocol:
    name: dubbo
    port: 12345

  registry:
    address: N/A
server:
  port: 8998